apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: inventory-orders
  labels:
    strimzi.io/cluster: my-cluster
    scenario: "1"
spec:
  partitions: 10
  replicas: 1
  config:
    retention.ms: -1
    cleanup.policy: compact
