apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafka-demo
  name: inventory-mysql
  annotations:
    description: "A mysql database pre-populated with example data, courtesy of the Debezium project"
    url: "https://debezium.io/documentation/reference/tutorial.html"
  labels:
    app: inventory-mysql
    scenario: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-mysql
  template:
    metadata:
      labels:
        app: inventory-mysql
        scenario: "1"
    spec:
      containers:
        - name: inventory-mysql
          image: debezium/example-mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: debezium
            - name: MYSQL_USER
              value: mysqluser
            - name: MYSQL_PASSWORD
              value: mysqlpw
---
apiVersion: v1
kind: Service
metadata:
  namespace: kafka-demo
  name: inventory-mysql
  labels:
    scenario: "1"
spec:
  type: ClusterIP
  selector:
    app: inventory-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
